### ISSUE TITLE
Enable submitting non-json data to Secret.generic.vault.jet.crossplane.io

### ISSUE THREAD

**Issue by AaronME** [crossplane-contrib/provider-jet-vault#1]
### What problem are you facing?
The `vault_generic_secret` resource expects data to be formatted as JSON. It uses the Keys of this json to name secret fields when submitting them to vault.

An example Kubernetes Secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
stringData:
  exampleKey: '{"keyone": "valueone", "keytwo":"valuetwo"}'
type: Opaque
```

An example Vault Secret:
```yaml
---
apiVersion: generic.vault.jet.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: example-vault-secret
spec:
  forProvider:
    path: "secret/foo"
    dataJsonSecretRef:
      key: exampleKey
      name: example-secret
      namespace: default
```

The resulting secret in vault would look like this:
```bash
$ vault kv get secret/foo

===== Data =====
Key        Value
---        -----
keyone     valueone
keytwo     valuetwo
```

If the secret is not json-formatted, it will fail apply and not be created.

This creates several issues:
1. json-formatted secrets are often intended to be consumed _as_ json, not parsed out.
2. ConnectionDetails which are not already json formatted cannot be submitted to vault.

### How could Vault Provider help solve your problem?
Support submitting raw data to the resource via a `dataSecretRef` field. This field will signal the provider to json-encode the data and set this json-encoded string when submitting the resource for creation.

An example Kubernetes Secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
stringData:
  exampleKey: 'I am a connection secret'
type: Opaque
```

An example Vault Secret:
```yaml
---
apiVersion: generic.vault.jet.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: example-vault-secret
spec:
  forProvider:
    path: "secret/foo"
    dataSecretRef:
      key: exampleKey
      name: example-secret
      namespace: default
```

The resulting secret in vault would look like this:
```bash
$ vault kv get secret/foo

===== Data =====
Key           Value
---           -----
exampleKey    'I am a connection secret'
```

### Implementation

Adding the field can be achieved by [adding a tfconfig.ResourceOption](https://github.com/crossplane-contrib/provider-jet-aws/blob/8bdca62d0d21895bef9a07c601feb0274672bcb9/config/overrides.go#L315) to the spec. This option is then included by updating the [WithDefaultResourceFn](https://github.com/crossplane-contrib/provider-jet-aws/blob/8bdca62d0d21895bef9a07c601feb0274672bcb9/config/provider.go#L159). 

What is less clear is how to perform the pre-parsing. @muvaf has suggested this would involve writing a new [ExternalClient](https://github.com/upbound/provider-jet-vault/blob/1775d5114df851b640b4f0fa7956f859e9447e73/internal/controller/generic/secret/zz_controller.go#L41) for the provider. There is an open issue to fully document this approach [here](https://github.com/crossplane/terrajet/issues/235).
